name: Update website

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add version to doxyfile
      run: |
        echo "PROJECT_NUMBER = $(git describe --tags --abbrev=0)" >> docs/Doxyfile

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: 'docs/Doxyfile'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc

